# This file contains values from Cookiecutter

default_context:
  project_name: "spell-craft"
  project_description: "SpellCraft CLI is a Python project that generates command-line interfaces (CLIs) from configurations. Each CLI plugin is packaged as a separate module containing a configuration and a list of commands. Our nomenclature revolves around the concept of spells and incantations, where plugins are spells and commands are incantations."
  organization: "spell-craft"
  license: "MIT"
  minimal_python_version: 3.8
  github_name: "reedjones"
  email: "reedmjones@outlook.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
